### ISSUE TITLE
Wireless Speaker

### ISSUE THREAD

**Issue by GTRspotter** [davwheat/rail-announcements#94]
I noticed that when playing announcements on a wireless speaker, it doesn't sound like the voice.

**Comment by davwheat** [comment]
It's pretty likely that the issue here is with your wireless speaker or the device that drives it.

There's weirdness with my Bluetooth headphones on my phone where the chime doesn't work correctly.

I might be able to add some silence (or almost silence) to the start of announcements, but then that would be seen as lag on other speakers/devices.
